SEQUENCE_TIMEOUT = 5.0
GESTURE_HOLD_FRAMES = 5
NO_HAND_GRACE_FRAMES = 8

STATE_WAITING_FOR_THUMBS_UP = "WAITING_FOR_THUMBS_UP"
STATE_WAITING_FOR_OPEN_PALM = "WAITING_FOR_OPEN_PALM"
STATE_ACTIVE = "ACTIVE"

GESTURE_THUMBS_UP = "THUMBS_UP"
GESTURE_OPEN_PALM = "OPEN_PALM"
GESTURE_UNKNOWN = "UNKNOWN"
